services:
  - type: web
    name: employee-feedback-backend
    env: docker
    repo: https://github.com/RakshithaThirthakar/Employee-Feedback-system
    dockerfilePath: backend/Dockerfile
    buildCommand: docker-compose build backend
    startCommand: docker-compose up backend
    plan: free
    branch: main
    autoDeploy: true

  - type: web
    name: employee-feedback-frontend
    env: docker
    repo: https://github.com/RakshithaThirthakar/Employee-Feedback-system
    dockerfilePath: frontend/Dockerfile
    buildCommand: docker-compose build frontend
    startCommand: docker-compose up frontend
    plan: free
    branch: main
    autoDeploy: true
