services:
  - type: web
    name: employee-feedback-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    autoDeploy: true

  - type: web
    name: employee-feedback-frontend
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
